urls.py
from django.contrib import admin
from django.urls import path

#from keivproject.chahana.api.views import LoginView
from .views import CreateUserAPIView, CreateProfileAPIView
from . import views

app_name = 'chahana'

urlpatterns = [
    path('index/', views.index, name='index'),
    path('register/',views.user_register, name='register'),
    path('login/', views.user_login, name='login'),
    path('user_profile/',views.user_profile),
    path('profile/',views.user_profile, name='profile'),
    path('create/',CreateUserAPIView.as_view()),
    path('obtain/', views.authenticate_user, name='obtain'),
    path('createprofile/',CreateProfileAPIView.as_view()),
    path('follow/',views.follow,name='follow'),
    path('followusers/<int:id>/',views.followinguserss,name='followinguserss'),
    path('delete/<int:id>/',views.deleteUsers,name='deleteusers'),
    path('completeDetails/<int:id>/',views.completeUser,name="completeUser"),
    path('create1/<int:id>', views.create1,name='create1'),
    path('wishlist/',views.HomePageView.as_view()),
	path('product/<int:id>',views.productClass.as_view({'get': 'list'})),
    path('following/',views.Foll.as_view()),
    path('search/',views.search,name='search'),
    path('apioffollowfunction/', views.follow)



]

templates/chahana/following.html
<html>
<head></head>
<body>
<h1>Welcome {{username}}</h1>
	<form method='post' action={% url 'chahana:follow' %}>
		{% csrf_token %}
	<input type="text" name="firstuser" value="{{username}}">
	<select name="secondname">
	  <option value="secondname" selected disabled hidden>Choose here</option>
		{% for i in use %}
	  <option value="{{i.id}}">{{i.names}}</option>
		{% endfor %}
	</select>
	<input type="submit" value="Follow" id="clickMe">
	</form>
	<br>
	<script>
	$(document).ready(function(){
		$("#clickMe").click(function() {
		$.ajax({
			type:'POST',
			url:'/chahana/follow',
			data:{
				'fname':firstuser,
				'sname':secondname
			},
			dataType: 'json',
		});
	});
	});

	</script>
<a href="{% url 'chahana:followinguserss' user.id %}">Friends</a>
<a href="{% url 'chahana:create1' user.id %}">Make A Wish </a>





{% for i in wish %}
{{i.item_name}}
{% endfor %}
{{user.item_name}}
</body>
</html>

templates/chahana/followinguserss.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>Here are the friends that you followed !!</h1>
    {% for i in foll %}
      {% if i.following_name == user.username %}
        <a href="{% url 'chahana:completeUser' i.id %}">{{i.user}}</a>
        <form action="{% url 'chahana:deleteusers' i.id %}" method="post">
          {% csrf_token %}
          <input type="submit" value="Unfollow">
        </form>
        <br>
      {% endif %}
    {% endfor %}
  </body>
</html>

templates/chahana/helo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/chahana/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
      <form>
        {% csrf_token %}
        <input class="text" type="text" name="firstname" placeholder="Firstname" required="" id="firstname"><br>
        <input class="text" type="text" name="lastname" placeholder="Lastname" required="" id="lastname"><br>
        <label for="birthday">Birthdate</label>
        <input type="date" name="birthday" id="birthday" id="birthday"><br>
        <label>Bloodgroup</label>
         <!--<select class="form-control" id="blood" onclick="">-->
                    <!--<option disabled selected>Choose Here</option>-->
                    <!--{% for i in data %}-->
                    <!--<option value={{i}}>{{i}}</option>-->
                    <!--{% endfor %}-->
         <!--</select>-->



        <select name="bloodgroup">
            <
            <option value="A+">A+</option>
            <option value="B+">B+</option>
            <option value="AB+">AB+</option>
            <option value="A-">A-</option>
            <option value="B-">B-</option>
            <option value="O+">O+</option>
            <option value="O-">O-</option>
        </select><br>
          <input type="file" name="pic" src="prof2.jpg" placeholder="photo" id="photo">
        <input class="text" type="text" name="phonenumber" placeholder="phonenumber" required="" id="phonenumber">
        <button  id="submit" class="btn btn-primary">Submit </button>

    </form>

</head>
<body>
   <!--<script>-->
    <!--$(document).ready(function(){-->

    <!--$("#submit").click(function() { // using the unique ID of the button-->
        <!--console.log("This is test");-->

        <!--var firstname=$("#firstname").val();-->
        <!--var lastname=$("#lastname").val();-->
        <!--var birthday=$("#birthday").val();-->
        <!--var blood = $("#blood option:selected").text();-->
        <!--var photo = $("#photo").val();-->
        <!--var phonenumber = $("#phonenumber").val();-->


        <!--if(blood!="" && firstname!="" && lastname!="" && birthday!="" && blood!="Choose Here"&& photo!="" && phonenumber!=""){-->
        <!--console.log(firstname);-->
        <!--console.log(lastname);-->
        <!--console.log(birthday);-->
        <!--console.log(blood);-->
        <!--console.log(photo);-->
        <!--console.log(phonenumber)-->
         <!--var csrftoken = jQuery("[name=csrfmiddlewaretoken]").val();-->

                        <!--function csrfSafeMethod(method) {-->
                            <!--// these HTTP methods do not require CSRF protection-->
                            <!--return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));-->
                        <!--}-->
                        <!--// set csrf header-->
                        <!--$.ajaxSetup({-->
                            <!--beforeSend: function(xhr, settings) {-->
                                <!--if (!csrfSafeMethod(settings.type) && !this.crossDomain) {-->
                                    <!--xhr.setRequestHeader("X-CSRFToken", csrftoken);-->
                                <!--}-->
                            <!--}-->
                        <!--});-->

                         <!--$.ajax({-->
                            <!--type : "POST",-->
                            <!--url: "/chahana/user_profile/",-->
                            <!--data:{-->
                                <!--'first':firstname,-->
                                <!--'last':lastname,-->
                                <!--'birthday':birthday,-->
                                <!--'blood':blood,-->
                                <!--'photo':photo,-->
                                <!--'phonenumber':phonenumber-->

                            <!--},-->
                             <!--dataType: 'json',-->
                    <!--success: function (data) {-->
                      <!--if (data.is_taken) {-->
                        <!--alert("A user with this username already exists.");-->
                      <!--}-->
                    <!--},-->
                     <!--error: function (jqXHR, status, err) {-->
                            <!--alert("error found")-->
              <!--},-->
                        <!--});-->
               <!--}-->

       <!--});-->

 <!--});-->
<!--</script>-->
</body>
</html>

templates/chahana/index1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div class="container">



    <form  method="post" enctype="multipart/form-data">
        <!--<form action="/chahana/create" method="POST">#}-->
        {% csrf_token %}
        kfndskvnsdk
        {{ form.as_p }}
        <input type="submit" value="wish" id="clickMe">
    </form>

        <center>
             <table class="table" border="1">
        <br><tr>
            <th>Wish List Items</th>
        </tr>


            {% for each in give1 %}
                <tr>
                <td>{{ each.item_name }}</td>
                <td><a href="/edit1/{{ each.id }}">Edit </a><a href="/delete1/{{ each.id }}">Delete</a></td>
                </tr>
            {% endfor %}

    </table>



        </center>

    </div>
<script>
    $(document).ready(function(){
		$("#clickMe").click(function() {
		$.ajax({
			type:'POST',
			url:'/chahana/create1',
			data:{
				'iname':item_name,
				'imname':img_name,
			},
			dataType: 'json',
		});
	});
	});

</script>

</body>
</html>

templates/chahana/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

    <form method="post" action="">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Login" class="btn btn-outline-success">
    </form>
</head>
<body>

</body>
</html>

templates/chahana/nav.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<!-- Custom Theme files -->
<link href="chahana/style.css" rel="stylesheet" type="text/css" media="all" />
<!-- //Custom Theme files -->
<!-- web font -->
<link href="//fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,700,700i" rel="stylesheet">
<!-- //web font -->
</head>
<body>
	<!-- main -->
	<div class="main-w3layouts wrapper">
		<h1>Wish-List</h1>
		<div class="main-agileinfo">
			<div class="agileits-top">
				<form action="/chahana/register/" method="post">
                    {% csrf_token %}
					<input class="text" type="text" name="username" placeholder="Username" required=""><br>
					<input class="text email" type="email" name="email" placeholder="Email" required=""><br>
					<input class="text" type="password" name="password" placeholder="Password" required=""><br>
					<!--<input class="text w3lpass" type="password" name="confirm_password" placeholder="Confirm Password" required="">-->
					<div class="wthree-text">
						<label class="anim">
							<input type="checkbox" class="checkbox" required="">
							<span>I Agree To The Terms & Conditions</span>
						</label>
						<div class="clear"> </div>
					</div>
					<input type="submit" value="SIGNUP">
				</form>
				<p>Don't have an Account? <a href="/api/login"> Login Now!</a></p>
			</div>
		</div>
		<!-- copyright -->
		<div class="colorlibcopy-agile">
			<p>© 2018 Colorlib Signup Form. All rights reserved | Design by <a href="https://colorlib.com/" target="_blank">Colorlib</a></p>
		</div>
		<!-- //copyright -->
		<ul class="colorlib-bubbles">
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
		</ul>
	</div>
	<!-- //main -->
</html>

templates/chahana/nav1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'blog:post_list' %}">TAlkit</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
        <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
    </ul>
    <ul class="navbar-nav">
        {% if request.user.is_authenticated %}
        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <span>Hi {{ request.user }}</span>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'blog:user_logout' %}">Logout</a>

        </div>
      </li>
      {% else %}
      </li>
        <li class="nav-item">
            <a href="{% url 'blog:user_login' %}" class="nav-link">Login</a>
        </li>
        {% endif %}
    </ul>
  </div>
</nav>
</body>
</html>

templates/chahana/page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% for i in reg %}
        <a href="{% url 'chahana:user_profile' i.id %}">
            <button type="button" name="completeprofile" >
        Complete Profile</button>
        </a>

    {% endfor %}
</head>
<body>

</body>
</html>

templates/chahana/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
       <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">
    <script src="https://netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
    <script type='text/javascript' src='//code.jquery.com/jquery-1.8.3.js'></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.5.0/css/bootstrap-datepicker3.min.css">
    <script type='text/javascript' src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.5.0/js/bootstrap-datepicker.min.js"></script>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <form>
        {% csrf_token %}
        <input class="text" type="text" name="firstname" placeholder="Firstname" required="" id="firstname"><br>
        <input class="text" type="text" name="lastname" placeholder="Lastname" required="" id="lastname"><br>
        <label for="birthday">Birthdate</label>
        <input type="date" name="birthday" id="birthday" id="birthday"><br>
        <label>Bloodgroup</label>
         <select class="form-control" id="blood" onclick="">
                    <option disabled selected>Choose Here</option>
                    {% for i in data %}
                    <option value={{i}}>{{i}}</option>
                    {% endfor %}
         </select>
        <input type="file" name="pic" accept=".jpg|image/*" placeholder="photo" id="photo">
        <input class="text" type="text" name="phonenumber" placeholder="phonenumber" required="" id="phonenumber">


        <!--<select name="bloodgroup">-->
        <!--<option value="A+">A+</option>-->
        <!--<option value="B+">B+</option>-->
        <!--<option value="AB+">AB+</option>-->
        <!--<option value="A-">A-</option>-->
            <!--<option value="B-">B-</option>-->
            <!--<option value="O+">O+</option>-->
            <!--<option value="O-">O-</option>-->
        </select><br>
        <h1  id="submit"><span class="btn btn-primary">Submit </span></h1>
    </form>

   </head>
<body>
<script>
    $(document).ready(function(){

    $("#submit").click(function() { // using the unique ID of the button
        console.log("This is test");

        var firstname=$("#firstname").val();
        var lastname=$("#lastname").val();
        var birthday=$("#birthday").val();
        var blood = $("#blood option:selected").text();
        var photo = $("#photo").val();
        var phonenumber = $("#phonenumber").val();


        if(blood!="" && firstname!="" && lastname!="" && birthday!="" && blood!="Choose Here"&& photo!="" && phonenumber!=""){
        console.log(firstname);
        console.log(lastname);
        console.log(birthday);
        console.log(blood);
        console.log(photo);
        console.log(phonenumber);
         var csrftoken = jQuery("[name=csrfmiddlewaretoken]").val();

                        function csrfSafeMethod(method) {
                            // these HTTP methods do not require CSRF protection
                            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
                        }
                        // set csrf header
                        $.ajaxSetup({
                            beforeSend: function(xhr, settings) {
                                if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                                    xhr.setRequestHeader("X-CSRFToken", csrftoken);
                                }
                            }
                        });

                         $.ajax({
                            type : "POST",
                            url: "/chahana/user_profile/",
                            data:{
                                'first':firstname,
                                'last':lastname,
                                'birthday':birthday,
                                'blood':blood,
                                'photo':photo,
                                'phonenumber':phonenumber,

                            },
                             dataType: 'json',
                    success: function (data) {
                      if (data.is_taken) {
                        alert("A user with this username already exists.");
                      }
                    },
                     error: function (jqXHR, status, err) {
                            alert("error found")
              },
                        });
               }

       });

 });
</script>
</body>
</html>

templates/chahana/test.html
<!DOCTYPE html>
<html>
<head>
    <meta content="width=device-width, initial-scale=1" name="viewport">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
    <script>
    </script>
</head>
<body>
<form id="form" method="post">
    {% csrf_token %}
    <div class="container" style="text-align:center;padding-top:50px;">
        <div>
            <div style="display: inline-block;">
                <h3><span class="label label-default">Task: </span></h3>
            </div>

            <div style="display: inline-block;padding-left:25px;">
                <input class="form-control" id="ex1" name="text" type="text" value="Task Name" onfocus="this.value=''">
            </div>

        </div>
        <br>
        <div>
            <div style="display: inline-block;">
                <h3 style="padding-left:105px;"><span class="label label-default">Documents: </span></h3>
            </div>
            <div style="display: inline-block;padding-left:25px;">
                <select class="form-control" id="first_doc" onclick="">
                    <option disabled selected>Choose Here</option>
                    {% for i in data %}
                    <option value={{i.doc_name}}>{{i.doc_name }}</option>
                    {% endfor %}
                </select>
            </div>

            <div style="display: inline-block;padding-left:25px;">
                <select class="form-control" id="first_no">
                    <option disabled selected>Count</option>
                    {% for i in index %}
                    <option value={{i}}>{{i}}</option>
                    {% endfor %}
                </select>

            </div>

            <div style="display: inline-block;padding-left:20px;">
                <!--<h1 id="next" ><span class="btn btn-primary">Next </span></h1>-->
                <button id="next" type="button" class="btn btn-primary">Next</button>
            </div>
        </div>
        <br>

    </div>

</form>


<div class="container" style="padding-left:120px;">
    <h2 style="text-align:center;padding-top:30px;">Details</h2>
    <table class="table" id="td_val">
        <thead>
        <tr>
            <th>Task</th>
            <th>Document</th>
            <th>No_Of_Copies</th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody>
        <tr>

        </tr>
        </tbody>
    </table>
    <div style="display: inline-block;padding-left:450px;">
          <h1  id="sub"><span class="btn btn-primary">Submit </span></h1>
            <!--<button >Submit</button>-->
        </div>
</div>
<script>

$(document).ready(function(){

    $("#next").click(function() { // using the unique ID of the button
        var doc_name = $("#first_doc option:selected").text();
        var doc_no = $("#first_no option:selected").val();
        var task=$("#ex1").val();
        console.log(task)
        $('#result').append(doc_name);
        console.log(doc_name,doc_no,task)
        if(task!="Task Name" && doc_name!="Choose Here" && doc_no!="Count" && task!=""){
            var markup = "<tr><td>" + task + "</td> <td>" + doc_name + "</td> </td>"+"</td> <td>" + doc_no + "</td> <td><input class='btn btn-default' value='Remove' type='button' onClick='$(this).parent().parent().remove();'></td></tr>";
            $("table tbody").append(markup);
        }
        $("#remove").click(function(){
                    $(this).parent().parent().remove();

        });
    });
          $('#sub').click(function(e){

                var doc_val=[]
                var no_val=[]
                var oTable = document.getElementById('td_val');
                //gets rows of table
                var rowLength = oTable.rows.length;

                //loops through rows
                for (i = 1; i < rowLength; i++){


                  //gets cells of current row
                   var oCells = oTable.rows.item(i).cells;

                   //gets amount of cells of current row
                   var cellLength = oCells.length;

                   //loops through each cell in current row
                   for(var j = 0; j < cellLength-1; j++){
                          // get your cell info here

                          var cellVal = oCells.item(j).innerHTML;

                          console.log(cellVal);
                          if(j==1){
                            doc_val.push(cellVal);
                          }
                          if(j==2){
                            no_val.push(cellVal);
                          }

                       }

                }
                    e.preventDefault();
                    var task=$("#ex1").val();
                    if(task!="Task Name" && task!=""){
                        console.log(task)

                        // using jQuery
                        var csrftoken = jQuery("[name=csrfmiddlewaretoken]").val();

                        function csrfSafeMethod(method) {
                            // these HTTP methods do not require CSRF protection
                            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
                        }
                        // set csrf header
                        $.ajaxSetup({
                            beforeSend: function(xhr, settings) {
                                if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                                    xhr.setRequestHeader("X-CSRFToken", csrftoken);
                                }
                            }
                        });

                         $.ajax({
                            type : "POST",
                            url: "/insert-data/",
                            data:{
                                'doc':doc_val,
                                'no':no_val,
                                'task_val':task,

                            },
                             dataType: 'json',
                    success: function (data) {
                      if (data.is_taken) {
                        alert("A user with this username already exists.");
                      }
                    },
                     error: function (jqXHR, status, err) {
                            // do something
              },
                        });
                        }
       });
});


</script>
</body>
</html>